AWSTemplateFormatVersion: '2010-09-09'

Description: Windows-instance template which sets up on-premise machine which can be used to access a declared file server.

Parameters:
  VPC:
    Description: A dropdown list enabling the selection of the Id for the VPC.
    Type: 'AWS::EC2::VPC::Id'

  Subnet:
    Description: A dropdown list enabling the selection of the Id for the public subnet.
    Type: 'AWS::EC2::Subnet::Id'

  SecurityGroupIds:
    Description: A multi-selection list enabling the selection of one or more security groups.
    Type: 'List<AWS::EC2::SecurityGroup::Id>'

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the file server.
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.

  LatestWindowsAmiId:
    Description: A string-based resource path representing the latest Windows Amazon Machine Image (AMI) that should be used to create the instance.
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-windows-latest/Windows_Server-2019-English-Full-Base
    
Resources:
  WindowsInstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  
  WindowsInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        [Ref: WindowsInstanceRole]

  WindowsInstanceRolePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 
        Fn::Sub: "Windows-client-${AWS::StackName}"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:Get*'
              - 's3:List*'
            Resource: '*'
      Roles:
        [Ref: WindowsInstanceRole]


  WindowsInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 
        Ref: LatestWindowsAmiId
      KeyName: 
        Ref: KeyName
      InstanceType: t2.micro
      IamInstanceProfile: 
        Ref: WindowsInstanceProfile
      SecurityGroupIds: 
        Ref: SecurityGroupIds
      SubnetId: 
        Ref: Subnet
      Tags:
        - Key: Name
          Value: DE-Extract-Windows-Instance
      UserData: 
        Fn::Base64:
          'Fn::Join':
          - ''
          - - |
              #!/bin/bash
            - |
              yum install -y aws-cfn-bootstrap
            - |
              sudo su
            - |
              mkdir /temp
            - |
              aws s3 sync s3://de-extract-predict-payload/Pre_Script /temp
            - |
              chmod 755 /temp/prescript.sh
            - |
              cd /temp
            - |
              ./prescript.sh
            - |
              rm prescript.sh
  
  
  
      
Outputs:
  WindowsInstance:
    Description: Private IP address of the newly created File server EC2 instance
    Value: 
      Fn::GetAtt:
        - WindowsInstance
        - PrivateIp